server:
  port: 8082
  servlet:
    context-path: /bookmark
spring:
  profiles:
    active: prod
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # 自动创建表以及更新表结构，生产环境慎用
    show-sql: true # 打印执行的SQL
  h2:
    console:
      path: /h2-console
      enabled: true
